### 테스트 알림 보내기
POST http://localhost:8089/api/test-notification?userId=user123
Content-Type: application/json

### 전체 사용자에게 알림 보내기
POST http://localhost:8089/api/test-notification?userId=all
Content-Type: application/json

### 실사이트 테스트
POST http://moim.o-r.kr/api/test-notification?userId=user123
Content-Type: application/json
